name: Generate API Document Markdown from Python Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docstring-to-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Package
        run: pip install git+https://github.com/mjun0812/docstring2markdown.git

      - name: Generate Doc
        run: doc-to-md kunai

      - name: Git commit and push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update doc.md"
            git push
          fi
