name: Generate API Document

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docstring-to-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Package
        run: |
          pip install poetry
          poetry install --no-interaction

      - run: mkdocs gh-deploy --force
